### ISSUE TITLE
Bug Report: Impossible to win the Raffle

### ISSUE THREAD

**Issue by Ethanol48** [PatrickAlphaC/puppy-raffle-smartcon#1]
## Possible Lock of selectWinner function

I found a problem with the Smart Contract, that may lock the funds in the contract, in the following function we find the `refund` function that returns to the user the entranceFee and eliminates it from the players array, because of this the balance of the contract has been reduced, creating a problem.
    
```solidity
    function refund(uint256 playerIndex) public {
        address playerAddress = players[playerIndex];
        require(playerAddress == msg.sender, "PuppyRaffle: Only the player can refund");
        require(playerAddress != address(0), "PuppyRaffle: Player already refunded, or is not active");

        payable(msg.sender).sendValue(entranceFee);

        players[playerIndex] = address(0);
        emit RaffleRefunded(playerAddress);
    }
```

When `selectWinner()` is called, there is a  part of the function that will fail to execute, the variable `totalAmountCollected`

This variable depends on the players who are playing the game, but there isn't a way to track the players that have left the game, breaking the code, with this variable it's calculated the `fees` and the `prizePool` making this call `(bool success,) = winner.call{value: prizePool}("");` it would be imposible because of the refund of one player, it would return "Out of Funds" Error.

Making it imposible to win the raffle.

```solidity
function selectWinner() external {
        require(block.timestamp >= raffleStartTime + raffleDuration, "PuppyRaffle: Raffle not over");
        require(players.length >= 4, "PuppyRaffle: Need at least 4 players");
        uint256 winnerIndex =
            uint256(keccak256(abi.encodePacked(msg.sender, block.timestamp, block.difficulty))) % players.length;
        address winner = players[winnerIndex];
        
        
        /// Problematic variable
        uint256 totalAmountCollected = players.length * entranceFee;
        
        uint256 prizePool = (totalAmountCollected * 80) / 100;
        uint256 fee = (totalAmountCollected * 20) / 100;
        totalFees = totalFees + uint64(fee);

        uint256 tokenId = totalSupply();

        // We use a different RNG calculate from the winnerIndex to determine rarity
        uint256 rarity = uint256(keccak256(abi.encodePacked(msg.sender, block.difficulty))) % 100;
        if (rarity <= COMMON_RARITY) {
            tokenIdToRarity[tokenId] = COMMON_RARITY;
        } else if (rarity <= COMMON_RARITY + RARE_RARITY) {
            tokenIdToRarity[tokenId] = RARE_RARITY;
        } else {
            tokenIdToRarity[tokenId] = LEGENDARY_RARITY;
        }

        delete players;
        raffleStartTime = block.timestamp;
        previousWinner = winner;
        
        // Impossible function call
        (bool success,) = winner.call{value: prizePool}("");
        
        require(success, "PuppyRaffle: Failed to send prize pool to winner");
        _safeMint(winner, tokenId);
    }
```

With this code not being able to execute, the only way to move the funds out of the contract will be the task for each user to call the `refund()` function to obtain their ether back

**Comment by Ethanol48** [comment]
There isn't also a check for the `address(0)` when entering the raffle making it possible to burn ether and lose the NFT without the intention of doing it.

**Comment by Ethanol48** [comment]
I've worked for a couple of minutes fixing these issues, I'll create a Pull Request for the changes to be revised

**Comment by Ethanol48** [comment]
The [PR link](https://github.com/PatrickAlphaC/puppy-raffle-smartcon/pull/2)

**Comment by PatrickAlphaC** [comment]
Awesome work!!! This was for demo purposes, so I won't be merging any PRs.

But stay tuned... This will be on the test coming up ;)
